"""Export fitted :class:`ParamSet` to the C++ header layout used by RDKit.

RDKit (and Guillaume's ``rdkit-brian`` fork) embeds EEM parameters in
``Code/GraphMol/Descriptors/EEM.cpp`` as:

::

    const double kappa = 0.5125;
    const double A1[] = {0.0, /* Z=1 */ 2.5473, /* Z=2 */ 0.0, ...};
    const double B1[] = {0.0, /* Z=1 */ 1.1641, /* Z=2 */ 0.0, ...};
    /* A2/A3 and B2/B3 for higher bond-order atom types … */

This module emits a drop-in header snippet so a refit can be wired into
RDKit by patching ``EEM.cpp``. By default we emit the single-bond
``A1/B1`` arrays only; the multi-bond variants are stubs to fill in
when the :class:`EEMModel` is built with ``use_bond_order=True``.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from powelleem.types import ParamSet


# Maximum atomic number RDKit's EEM tables span (Br = 35, Iodine = 53 if user adds it).
_MAX_Z = 53


def _atom_type_to_z(atom_type: str) -> int | None:
    """Try to extract an atomic number from a 1-letter / 2-letter element symbol."""
    symbols = {
        "H": 1, "B": 5, "C": 6, "N": 7, "O": 8, "F": 9, "Si": 14, "P": 15,
        "S": 16, "Cl": 17, "Br": 35, "I": 53, "Sb": 51, "Se": 34, "As": 33,
    }
    # Strip any "-1", "-2", "-3" bond-order suffix
    base = atom_type.split("-")[0]
    return symbols.get(base)


def write_rdkit_eem_header(params: ParamSet, path: Path) -> None:
    """Emit an ``EEM_params.h``-style snippet from a :class:`ParamSet`.

    Layout
    ------
    - ``EEM_KAPPA`` macro for κ
    - ``EEM_A1[]``, ``EEM_B1[]`` arrays indexed by atomic number (0..MAX_Z)
    """
    A1 = [0.0] * (_MAX_Z + 1)
    B1 = [0.0] * (_MAX_Z + 1)
    for t_str, a, b in zip(params.atom_types, params.alpha, params.beta, strict=True):
        z = _atom_type_to_z(t_str)
        if z is None or z > _MAX_Z:
            continue
        # If multi-bond types collide on the same Z we keep the *last* one
        # written; better behaviour requires a richer rdkit-brian patch.
        A1[z] = float(a)
        B1[z] = float(b)

    lines: list[str] = []
    lines.append("/*")
    lines.append(" * Auto-generated by powelleem.io_rdkit.write_rdkit_eem_header().")
    lines.append(" * Patch this into RDKit's Code/GraphMol/Descriptors/EEM.cpp.")
    lines.append(" */")
    lines.append("")
    lines.append(f"const double kappa = {params.kappa:.6g};")
    lines.append("")
    _emit_array(lines, "A1", A1)
    lines.append("")
    _emit_array(lines, "B1", B1)
    lines.append("")
    # Placeholder multi-bond arrays so EEM.cpp still compiles unchanged.
    _emit_array(lines, "A2", [0.0] * (_MAX_Z + 1))
    lines.append("")
    _emit_array(lines, "A3", [0.0] * (_MAX_Z + 1))
    lines.append("")
    _emit_array(lines, "B2", [0.0] * (_MAX_Z + 1))
    lines.append("")
    _emit_array(lines, "B3", [0.0] * (_MAX_Z + 1))
    lines.append("")

    path.write_text("\n".join(lines))


def _emit_array(lines: list[str], name: str, values: list[float]) -> None:
    formatted = ", ".join(f"{v:.4f}" for v in values)
    lines.append(f"const double {name}[] = {{{formatted}}};")
